CREATE DATABASE IF NOT EXISTS sistema_juegos;

USE sistema_juegos;

CREATE TABLE IF NOT EXISTS USUARIO (
    ID_U INT AUTO_INCREMENT PRIMARY KEY,
    Nombre_Usuario VARCHAR(50) NOT NULL,
    Correo_Electronico VARCHAR(100) NOT NULL UNIQUE,
    Contrasena VARCHAR(255) NOT NULL,
    Rol BOOLEAN DEFAULT FALSE,
    Rango BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS EQUIPO (
    ID_E INT AUTO_INCREMENT PRIMARY KEY,
    Nombre_Equipo VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS INTEGRA (
    ID_U INT PRIMARY KEY,
    ID_E INT NOT NULL,
    CONSTRAINT FK_INTEGRA_USUARIO
        FOREIGN KEY (ID_U) REFERENCES USUARIO(ID_U),
    CONSTRAINT FK_INTEGRA_EQUIPO
        FOREIGN KEY (ID_E) REFERENCES EQUIPO(ID_E)
);

CREATE TABLE IF NOT EXISTS JUEGO (
    ID_J INT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL,
    Descripcion VARCHAR(255),
    Puntos_Maximos INT NOT NULL
);

CREATE TABLE IF NOT EXISTS JUE_PAR (
    ID_P INT AUTO_INCREMENT PRIMARY KEY,
    ID_U INT NOT NULL,
    ID_J INT NOT NULL,
    Fecha DATETIME NOT NULL,
    Puntos INT DEFAULT 0,
    CONSTRAINT FK_JUEPAR_USUARIO
        FOREIGN KEY (ID_U) REFERENCES USUARIO(ID_U),
    CONSTRAINT FK_JUEPAR_JUEGO
        FOREIGN KEY (ID_J) REFERENCES JUEGO(ID_J)
);

CREATE TABLE IF NOT EXISTS ADMIN_U (
    ID_Adm_U INT AUTO_INCREMENT PRIMARY KEY,
    ID_Usu INT NOT NULL,
    ID_Adm INT NOT NULL,
    Fecha DATETIME NOT NULL,
    Accion VARCHAR(255) NOT NULL,
    CONSTRAINT FK_ADMINU_USUARIO
        FOREIGN KEY (ID_Usu) REFERENCES USUARIO(ID_U),
    CONSTRAINT FK_ADMINU_ADMINISTRADOR
        FOREIGN KEY (ID_Adm) REFERENCES USUARIO(ID_U)
);

CREATE TABLE IF NOT EXISTS ADMIN_J (
    ID_Adm_J INT AUTO_INCREMENT PRIMARY KEY,
    ID_Usu INT NOT NULL,
    ID_Jue INT NOT NULL,
    Fecha DATETIME NOT NULL,
    Accion VARCHAR(255) NOT NULL,
    CONSTRAINT FK_ADMINJ_ADMINISTRADOR
        FOREIGN KEY (ID_Usu) REFERENCES USUARIO(ID_U),
    CONSTRAINT FK_ADMINJ_JUEGO
        FOREIGN KEY (ID_Jue) REFERENCES JUEGO(ID_J)
);